//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 08:03:19 PM CEST 
//


package nl.openweb.jcr.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.openweb.hippo.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Value_QNAME = new QName("http://www.jcp.org/jcr/sv/1.0", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.openweb.hippo.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NodeBean }
     * 
     */
    public NodeBean createNode() {
        return new NodeBean();
    }

    /**
     * Create an instance of {@link PropertyBean }
     * 
     */
    public PropertyBean createProperty() {
        return new PropertyBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jcp.org/jcr/sv/1.0", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<>(_Value_QNAME, String.class, null, value);
    }

}
